#!/bin/sh /etc/rc.common
# Copyright (C) 2023 沉默の金 <cmzj11@gmail.com>
# Copyright (C) 2022 Lean <coolsnowwolf@gmail.com>
# Copyright (C) 2019-2021 Tianling Shen <cnsztl@immortalwrt.org>

START=90
STOP=10

EXTRA_COMMANDS="check_status"
EXTRA_HELP="	check_status Check running status of BBR"

inital_conf(){
	config_load "bbrswitch"
    config_get bbr_cca "config" "bbr_cca" "0"
	[ ! -e "/lib/modules/$(uname -r)/tcp_bbr.ko" ] && bbr_cca="0"
}

start(){
	inital_conf

	if [ "${bbr_cca}" -eq "1" ];  then
		sysctl -w net.ipv4.tcp_congestion_control="bbr"
		sysctl -w net.core.default_qdisc=cake
	else
		sysctl -w net.ipv4.tcp_congestion_control="cubic"
		sysctl -w net.core.default_qdisc=cake
	fi
}

stop(){
	inital_conf
	sysctl -w net.ipv4.tcp_congestion_control="cubic"
    sysctl -w net.core.default_qdisc=cake
}

restart(){
	stop
	start
}

check_status() {
    case "$1" in
    "bbr")
        if [ "$(cat /proc/sys/net/ipv4/tcp_congestion_control)" = "bbr" ]; then
            exit 0
        else
            exit 1
        fi
        ;;
    *)
        exit 2
        ;;
    esac
}