#!/bin/sh /etc/rc.common
# Copyright (C) 2023 沉默の金 <cmzj11@gmail.com>
# Copyright (C) 2022 Lean <coolsnowwolf@gmail.com>
# Copyright (C) 2019-2021 Tianling Shen <cnsztl@immortalwrt.org>

START=90
STOP=10

EXTRA_COMMANDS="check_status"
EXTRA_HELP="	check_status Check running status of BBR"

inital_conf(){
	config_load "bbrswitch"
    config_get bbr_cca "config" "bbr_cca" "0"
	[ ! -e "/lib/modules/$(uname -r)/tcp_bbr.ko" ] && bbr_cca="0"
}

start(){
	inital_conf

	if [ "${bbr_cca}" -eq "1" ];  then
		sysctl -w net.ipv4.tcp_congestion_control="bbr"
		sysctl -w net.core.default_qdisc=fq_codel
	else
		sysctl -w net.ipv4.tcp_congestion_control="cubic"
		sysctl -w net.core.default_qdisc=pfifo_fast
	fi
}

stop(){
	inital_conf

	if [ "${bbr_cca}" -eq "1" ];  then
	sysctl -w net.ipv4.tcp_congestion_control="cubic"
    sysctl -w net.core.default_qdisc=pfifo_fast
	fi
}

restart(){
	stop
	start
}

check_status(){
	case "$1" in
	"bbr")
		[ "x$(cat "/proc/sys/net/ipv4/tcp_congestion_control" 2>"/dev/null")" = "xbbr" ] && \
			exit 0 || exit 1
		;;
	*)
		exit 2
		;;
	esac
	if [ "$msg" != "" ] && { [ $# = 1 ] || { [ $# = 2 ] && [ "$2" = 1 ]; }; }; then
    	echo -n "$msg"
	fi
	exit "$exit_code"
}